[project]
name = "mcp-server-vector-search"
version = "0.1.0"
description = "Semantic search across your knowledge graph."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.12.2",
    "mcp[cli]>=1.8.0",
    "neo4j>=5.28.1",
    "openai>=1.78.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.0",
    "sentence-transformers>=4.1.0",
]

[project.scripts]
mcp-server-vector-search = "mcp_server_vector_search:main"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
